### ISSUE TITLE
Extend webservice to support obtaining unoconv version and supported formats

### ISSUE THREAD

**Issue by zrrrzzt** [zrrrzzt/tfk-api-unoconv#1]
From https://github.com/zrrrzzt/docker-unoconv-webservice/issues/4 

To help with preventing errors, would it be possible to call the webservice and obtain version and support format information?

**Comment by eugeneventer** [comment]
@zrrrzzt a /formats call would be great, returning some json ;)?

Now that I think of it, the version information is probably not that critical, but /version would work

**Comment by zrrrzzt** [comment]
Got to look at it before your answer. Blame the timezones :-)

I'll add som more tests and update the docker later today (CET).

Regarding version: I suppose you want the result of ```$ unoconv --version``` That is not supported atm in https://www.npmjs.com/package/unoconv2

If you need the information you'll have to attach a terminal to the running docker.

```$ docker exec -i -t <containerId> /bin/bash```
```root@<containerId>:/src# unoconv --version```
```
unoconv 0.6
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1]
LibreOffice 4.3
```

**Comment by eugeneventer** [comment]
Haha, cool!

Looking forward to it (nzdt) and thanks for your help! :)

**Comment by zrrrzzt** [comment]
Fixed. Updated. Closed 🎆
