### ISSUE TITLE
Removing uploaded files

### ISSUE THREAD

**Issue by daneshka** [zrrrzzt/tfk-api-unoconv#60]
The server keeps all of the uploaded files in "uploads" folder.
It has to delete them after sending the result, back to the client.

**Comment by zrrrzzt** [comment]
The original file is deleted after the converted file are returned to the client. At least that is what is supposed to happen.

The previous version did no cleanup original files if the conversion failed. The newest version (3.0.0) will handle that as well.

If your server still keeps the uploaded files please take a look at the logs and make sure the process is allowed to delete files.

**Comment by daneshka** [comment]
Thank you for your response.
I'm using version 2.2.3.  I'll upgrade it.

**Comment by zrrrzzt** [comment]
@daneshka feel free to reopen if your problems continues.
