### ISSUE TITLE
Is there any way to set the default timeout?

### ISSUE THREAD

**Issue by daneshka** [zrrrzzt/tfk-api-unoconv#79]
I have lots of files that I receive "socket hang up" on the conversion but, few minutes after when I see the logs It shows "Finished converting".
Is there any way to change the default timeout?

PS: I already increased the timeout on the caller side.

**Comment by zrrrzzt** [comment]
As far as I know you can configure timeouts for hapi (the web server) for each route on server and socket level.
I guess all I have to do is to support setting these values as env-variables.

I'll look into it.
