### ISSUE TITLE
LibreOffice Version

### ISSUE THREAD

**Issue by AvnerCohen** [zrrrzzt/tfk-api-unoconv#80]
I could well be missing something, the libreoffice packaged is 5.2.7.2
Will it be possible to updated that to latest version?

Or is it something I'm doing wrong?

**Comment by zrrrzzt** [comment]
By version number of LibreOffice I guess you refer to the dockerized version of this module through the Dockerfile from this repo or https://github.com/zrrrzzt/tfk-api-unoconv/blob/master/Dockerfile or this repo https://github.com/zrrrzzt/docker-unoconv-webservice.
If that's correct you can upgrade the version of LibreOffice by creating your own Dockerfile.

This is the base image I use https://github.com/telemark/docker-node-unoconv/blob/master/Dockerfile.

Hope that'll help you :-)

**Comment by AvnerCohen** [comment]
Thanks. I thought this was old version that could be causing the behavior I see (request is getting stuck), but manually installing this seems to indicate the issue is somewhere else.
Thanks, this does help !

**Comment by zrrrzzt** [comment]
@AvnerCohen are you trying to convert large files? After his issue https://github.com/zrrrzzt/tfk-api-unoconv/issues/79 I made it possible to allow longer timeouts

**Comment by AvnerCohen** [comment]
Thanks @zrrrzzt I work o the conversion with many files, some are larger than others.
The problem I see seems to be core to the PDF converter of libreoffice.
Some specific files are causing the converter to hang forever (across OSs and Versions).
This happens directly when I run soffice --headless, so not even UNO related.

Given I need a more stable solution, I think I'll have to look at options beyond Open Office.
